package com.cookandroid.stoneagedc.kindOfPet

import com.cookandroid.stoneagedc.R

object PetList {
    var petDataList = ArrayList<PetItem>()
     init {
        petDataList.add(PetItem(R.drawable.angiro, "얀기로", "1.5티어","공격",R.drawable.skill_angiro))
        petDataList.add(PetItem(R.drawable.giro, "기로", "1.5티어","공격",R.drawable.skill_giro))
        petDataList.add(PetItem(R.drawable.moonwolf, "문울프", "1.5티어","공격",R.drawable.skill_monwolf))
        petDataList.add(PetItem(R.drawable.crab, "크랩", "1.5티어","공격",R.drawable.skill_crab))
        petDataList.add(PetItem(R.drawable.berfuce, "베르푸스", "2티어","공격",R.drawable.skill_berfus))
        petDataList.add(PetItem(R.drawable.cue, "큐이", "2티어","공격",R.drawable.skill_cue))
        petDataList.add(PetItem(R.drawable.gordon, "고르돈", "2티어","공격",R.drawable.skill_gorgon))
        petDataList.add(PetItem(R.drawable.trarofo, "트라로포", "2티어","공격",R.drawable.skill_trarofo))
        petDataList.add(PetItem(R.drawable.berga, "베르가", "2티어","공격",R.drawable.skill_berga))
        petDataList.add(PetItem(R.drawable.jag, "쟈그", "2티어","공격",R.drawable.skill_zag))
        petDataList.add(PetItem(R.drawable.ggomi, "꼬미", "2티어","공격",R.drawable.skill_ggomi))
        petDataList.add(PetItem(R.drawable.fino, "피노", "2티어","공격",R.drawable.skill_fino))
        petDataList.add(PetItem(R.drawable.cucuro, "쿠쿠르", "3티어","공격",R.drawable.skill_cucur))
        petDataList.add(PetItem(R.drawable.baebo, "베이보", "3티어","공격",R.drawable.skill_baebo))
        petDataList.add(PetItem(R.drawable.falteon, "팔케온", "3티어","공격",R.drawable.skill_falcaon))
        petDataList.add(PetItem(R.drawable.gurumaru, "구루마루", "3티어","공격",R.drawable.skill_gurumaru))
        petDataList.add(PetItem(R.drawable.moga1, "모가", "4티어","공격",R.drawable.skill_moga))
        petDataList.add(PetItem(R.drawable.ftecus, "고테쿠스", "4티어","공격",R.drawable.skill_gotecus))
        petDataList.add(PetItem(R.drawable.beron, "베론", "4티어","공격",R.drawable.skill_beron))
        petDataList.add(PetItem(R.drawable.fingko, "핑코", "1티어","제어",R.drawable.skill_fox))
        petDataList.add(PetItem(R.drawable.ragogo, "라고고", "1티어","제어",R.drawable.skill_rabiru))
        petDataList.add(PetItem(R.drawable.firenosdon, "파이어노스돈", "1티어","제어",R.drawable.skill_nosdon))
        petDataList.add(PetItem(R.drawable.otutu, "오투투", "1.5티어","제어",R.drawable.skill_otutu))
        petDataList.add(PetItem(R.drawable.mui, "무이", "1.5티어","제어",R.drawable.skill_mue))
        petDataList.add(PetItem(R.drawable.bakseulrabbit, "백설토끼", "1.5티어","제어",R.drawable.skill_rabbit))
        petDataList.add(PetItem(R.drawable.fingki, "핑키", "2티어","제어",R.drawable.skill_bluestar))
        petDataList.add(PetItem(R.drawable.agoa, "아고아", "2티어","제어",R.drawable.skill_agoa))
        petDataList.add(PetItem(R.drawable.kamare, "카미르", "2티어","제어",R.drawable.skill_kamire))
        petDataList.add(PetItem(R.drawable.bongbong, "봉봉", "2티어","제어",R.drawable.skill_bongbong))
        petDataList.add(PetItem(R.drawable.fentas, "펜타스", "4티어","제어",R.drawable.skill_fentas))
        petDataList.add(PetItem(R.drawable.baroroks, "바로로크스", "4티어","제어",R.drawable.skill_barokrus))
        petDataList.add(PetItem(R.drawable.golfwolf, "골드로비", "OP","치료",R.drawable.skill_goldlobi))
        petDataList.add(PetItem(R.drawable.dorabis, "도라비스", "1티어","치료",R.drawable.skill_dorabis))
        petDataList.add(PetItem(R.drawable.bammi, "밤미", "1티어","치료",R.drawable.skill_bammi))
        petDataList.add(PetItem(R.drawable.monasif, "모나시프", "2티어","치료",R.drawable.skill_monasif))
        petDataList.add(PetItem(R.drawable.kaku, "카쿠", "3티어","치료",R.drawable.skill_kaku))
        petDataList.add(PetItem(R.drawable.manmo, "만모", "1티어","방어",R.drawable.skill_manmo))
        petDataList.add(PetItem(R.drawable.buke, "북이(딜북이)", "1티어","방어",R.drawable.skill_buke))
        petDataList.add(PetItem(R.drawable.duford, "듀포드", "1티어","방어",R.drawable.skill_duford))
        petDataList.add(PetItem(R.drawable.manmo, "만모(탑승)", "1.5티어","방어",R.drawable.skill_manmo))
        petDataList.add(PetItem(R.drawable.frakitos, "프라키토스", "1.5티어","방어",R.drawable.skill_frakitos))
        petDataList.add(PetItem(R.drawable.bubi, "부비", "2티어","방어",R.drawable.skill_bubi))
        petDataList.add(PetItem(R.drawable.duri, "두리", "2티어","방어",R.drawable.skill_duri))
        petDataList.add(PetItem(R.drawable.katarkas, "카타르카스", "3티어","방어",R.drawable.skill_katarkas))
        petDataList.add(PetItem(R.drawable.stolarge, "스토라지", "3티어","방어",R.drawable.skill_stolarge))
        petDataList.add(PetItem(R.drawable.sillingka, "살링카", "4티어","방어",R.drawable.skill_silringka))
        petDataList.add(PetItem(R.drawable.mogaros, "모가로스", "1티어","광역",R.drawable.skill_mogaros))
        petDataList.add(PetItem(R.drawable.mogaros, "모가로스(탑승)", "1티어","광역",R.drawable.skill_mogaros))
        petDataList.add(PetItem(R.drawable.sandizard, "샌디쟈드", "1티어","광역",R.drawable.skill_sandizard))
        petDataList.add(PetItem(R.drawable.tiragos, "티라고스", "1티어","광역",R.drawable.skill_tirano))
        petDataList.add(PetItem(R.drawable.kroton, "크로톤", "2티어","광역",R.drawable.skill_kroton))
        petDataList.add(PetItem(R.drawable.kaki, "카키", "2티어","광역",R.drawable.skill_kaki))
        petDataList.add(PetItem(R.drawable.gigaros, "기가로스", "2티어","광역",R.drawable.skill_gigaros))
        petDataList.add(PetItem(R.drawable.hubo, "휴보", "4티어","광역",R.drawable.skill_hubo))
    }

}